version: '2'
volumes:
    sense-data:
services:
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'HOME_DASHBOARD_UID=balenaSense'
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_SESSION_PROVIDER=memory'
        - 'GF_AUTH_ANONYMOUS_ENABLED=true'
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
  mqtt:
    image: arm32v6/eclipse-mosquitto:1.6.8
    hostname: mqtt
    container_name: mqtt
    ports:
      - "1883:1883"
    restart: always
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'settings:/data'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  fbcp:
    image: balenablocks/fbcp
    privileged: true
